### ISSUE TITLE
JSON returns error

### ISSUE THREAD

**Issue by batumulia** [lgc-4/one.com-ddns-python-script#7] opened 2023-02-21 06:18 UTC
When running the script the following error comes up. It seems to have issues getting data from JSON?

```python3 ./one_com_ddns_new.py
Detected IP: *.*.*.*
Logging in...
Login successful.
Setting active domain to: *.*
Getting Records
Traceback (most recent call last):
File "/home/pi/./one_com_ddns_new.py", line 178, in <module>
records = getCustomRecords(s, DOMAIN)
File "/home/pi/./one_com_ddns_new.py", line 145, in getCustomRecords
return json.loads(getres)["result"]["data"]
File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by lgc-4** [comment] 2023-02-21 10:40
Hi, thanks for your report.


So far I have only been able to reproduce this error when using an invalid domain. Maybe double check that you entered the correct domain. If that doesn't solve the issue I will need some additional information.


Entering a domain that includes certain special characters can make this script throw this error. This is because the one.com API will either return a 503 error if the domain includes a `%` sign, or will require a browser check, for example if the domain is set to `*.*`. I am not sure that this is the cause of your issue, but it could have something to do with it.

Also, just a friendly heads-up: If you wrap your code or error message in triple backticks
````
```
like this
```
````
it will look a lot neater and will be easier to read.

**Comment by batumulia** [comment] 2023-02-21 10:52
> Hi, thanks for your report.
> 
> So far I have only been able to reproduce this error when using an invalid domain. Maybe double check that you entered the correct domain. If that doesn't solve the issue I will need some additional information.
> 
> Entering a domain that includes certain special characters can make this script throw this error. This is because the one.com API will either return a 503 error if the domain includes a `%` sign, or will require a browser check, for example if the domain is set to `*.*`. I am not sure that this is the cause of your issue, but it could have something to do with it.
> 
> Also, just a friendly heads-up: If you wrap your code or error message in triple backticks
> 
> ```
> ```
> like this
> ```
> ```
> 
> it will look a lot neater and will be easier to read.

Thanks for the tip :) Never used Git before so was struggling to find it.

I run your script on a Pi and found that there is a 'pycache' folder. I have now (temporarily) deleted the folder and ran the script again. It worked once, but running it a second time gave me another set of errors (probably because I was running it too many times after each other). I'll try again in a few hours to see if that was indeed the problem or not. I'll keep you updated :)

**Comment by lgc-4** [comment] 2023-02-21 11:29
If by "another set of errors" you mean a message that looks something like this:

```
IP Address hasn't changed. Aborting.
```

that is intended behaviour of the script. Make sure you delete the `lastip.txt` file before trying to run the script again, or alternatively set `CHECK_IP_CHANGE` to `False`.

If that is not what you mean, be sure to include the error message in your comments.

Every seemingly irrelevant bit of information could possibly help solving the problem ;)

I guess it could be rate limiting by one.com, but I highly doubt that. I have not experienced any sort of rate limiting during the development of this script at all so far.

**Comment by lgc-4** [comment] 2023-05-23 14:26
Closing this issue for now as I'm guessing it's been resolved

Feel free to open another issue if you're still having trouble.

**Closed as completed by lgc-4** 2023-05-23 14:26 UTC
